name       : grub-customizer
version    : 5.1.0
release    : 7
source     :
    - https://launchpad.net/grub-customizer/5.1/5.1.0/+download/grub-customizer_5.1.0.tar.gz : 532f793eea4c6ee6cde4bc987966fa1924946c1da5e3c7b4d4a97f2689661ee0
license    : GPL-3.0-or-later
component  : system.utils
summary    : Grub Customizer is a graphical interface to configure the GRUB2/BURG settings and menuentries
description: |
    Grub Customizer is a graphical interface to configure the GRUB2/BURG settings and menuentries
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libarchive)
    - pkgconfig(openssl)
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr ..
build      : |
    %make -C build
install    : |
    %make_install -C build
