name        : grub-customizer
version     : 4.0.6
release     : 1
source      :
    - https://launchpad.net/grub-customizer/4.0/4.0.6/+download/grub-customizer_4.0.6.tar.gz : 8cdb9f130530120cc8be0fe568c2349194d34d565d2e9700006da39793f1f2e2
license     : GPL-3.0
summary     : Grub Customizer
builddeps   :
    - pkgconfig(libarchive)
    - pkgconfig(openssl)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(atkmm-1.6)
    - pkgconfig(glibmm-2.4)
description : |
    Grub Customizer is a graphical interface to configure the GRUB2/BURG settings and menuentries
    Features:
    * move, remove or rename menuentries (they stey updatable by update-grub)
    * edit the contents of menuentries or create new ones (internally it edits the 40_custom)
    * support for GRUB2 and BURG
    * reinstallation of the bootloader to MBR
    * settings like default operating system, kernel params, background image and text colors etc.
    * changing the installed operating system by running on a live cd
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
