name       : grub-customizer
version    : 5.0.6
release    : 2
source     :
    - https://launchpad.net/grub-customizer/5.0/5.0.6/+download/grub-customizer_5.0.6.tar.gz : c5a0d21c08b2215170b96294c7d7d96bd7588302b737bb3c06a1112bc074bdd3
license    : GPL-3.0
component  : system.utils
summary    : Grub Customizer
builddeps  :
    - pkgconfig(libarchive)
    - pkgconfig(openssl)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(atkmm-1.6)
    - pkgconfig(glibmm-2.4)
description: |
    Grub Customizer is a graphical interface to configure the GRUB2/BURG settings and menuentries
    Features:
    * move, remove or rename menuentries (they stey updatable by update-grub)
    * edit the contents of menuentries or create new ones (internally it edits the 40_custom)
    * support for GRUB2 and BURG
    * reinstallation of the bootloader to MBR
    * settings like default operating system, kernel params, background image and text colors etc.
    * changing the installed operating system by running on a live cd
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
