name       : grub-customizer
version    : 5.2.3
release    : 12
source     :
    - https://launchpad.net/grub-customizer/5.2/5.2.3/+download/grub-customizer_5.2.3.tar.gz : 2e357b114f4f5ebb868cb249d9ff60512d7ec49131314d378212717cd085bd21
homepage   : https://launchpad.net/grub-customizer
license    : GPL-3.0-or-later
component  : system.utils
summary    : Grub Customizer is a graphical interface to configure the GRUB2/BURG settings and menuentries
description: |
    Grub Customizer is a graphical interface to configure the GRUB2/BURG settings and menuentries
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libarchive)
    - pkgconfig(openssl)
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr ..
build      : |
    %make -C build
install    : |
    %make_install -C build
