name       : grub-customizer
version    : 5.1.0
release    : 4
source     :
    - https://launchpad.net/grub-customizer/5.1/5.1.0/+download/grub-customizer_5.1.0.tar.gz : 532f793eea4c6ee6cde4bc987966fa1924946c1da5e3c7b4d4a97f2689661ee0
license    : GPL-3.0
component  : system.utils
summary    : Grub Customizer
builddeps  :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(glibmm-2.4)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libarchive)
    - pkgconfig(openssl)
description: |
    Grub Customizer is a graphical interface to configure the GRUB2/BURG settings and menuentries
    Features:
    * move, remove or rename menuentries (they stey updatable by update-grub)
    * edit the contents of menuentries or create new ones (internally it edits the 40_custom)
    * support for GRUB2 and BURG
    * reinstallation of the bootloader to MBR
    * settings like default operating system, kernel params, background image and text colors etc.
    * changing the installed operating system by running on a live cd
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
